projects/PlacementManagement/force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

projects/PlacementManagement/force-app/main/default/classes/ApplicationTriggerHandler.cls
public class ApplicationTriggerHandler {

    public static void beforeInsert(List<Application__c> applications){

        ApplicationService.validateApplications(applications);

    }

    public static void beforeUpdate(List<Application__c> newApplications, Map<Id, Application__c> oldMap){
        for(Application__c a : newApplications){
            Application__c old = oldMap.get(a.Id);
            if(old.Status__c != 'Shortlisted' && a.Status__c == 'Shortlisted'){
                System.debug('STATUS CHANGED TO SHORTLISTED');
            }
        }

    }

    public static void afterUpdate(List<Application__c> newApplications, Map<Id, Application__c> oldMap){
        ApplicationService.processShortlistedApplications(newApplications, oldMap);
    }
}